import 'package:freezed_annotation/freezed_annotation.dart';
import 'organization_profile.dart';

part 'threat_profile.freezed.dart';
part 'threat_profile.g.dart';

/// A threat named in plain language — for non-technical users.
@freezed
class NamedThreat with _$NamedThreat {
  const factory NamedThreat({
    required String techniqueId,     // e.g. 'T1566'
    required String plainName,       // e.g. 'Fake emails (Phishing)'
    required String plainDescription,// e.g. 'Attackers send emails pretending to be...'
    required String riskReason,      // e.g. 'Healthcare is the #1 phishing target'
    required double riskScore,       // 0–10
    required int priority,           // 1 = highest
  }) = _NamedThreat;

  factory NamedThreat.fromJson(Map<String, dynamic> json) =>
      _$NamedThreatFromJson(json);
}

/// A coverage suggestion — what controls the user declared map to.
@freezed
class CoverageSuggestion with _$CoverageSuggestion {
  const factory CoverageSuggestion({
    required String techniqueId,
    required String suggestedLevel,  // 'covered' | 'partiallyCovered' | 'notCovered'
    required String reason,          // e.g. 'MFA covers Valid Accounts partially'
    required String controlSource,   // e.g. 'MFA'
  }) = _CoverageSuggestion;

  factory CoverageSuggestion.fromJson(Map<String, dynamic> json) =>
      _$CoverageSuggestionFromJson(json);
}

/// The computed threat profile for an organization.
/// Generated by ThreatProfileService from the OrganizationProfile.
@freezed
class ThreatProfile with _$ThreatProfile {
  const factory ThreatProfile({
    // Source
    required String organizationId,
    required OrgSector sector,

    // Overall posture
    required double baselineRiskScore,   // 0–100 before any coverage applied
    required String riskLevel,           // 'Critical' | 'High' | 'Medium' | 'Low'
    required String riskSummary,         // One-sentence plain English summary

    // Prioritised threats for this org (top 10)
    @Default([]) List<NamedThreat> topThreats,

    // Priority technique IDs (ordered by relevance to this org)
    @Default([]) List<String> priorityTechniqueIds,

    // Coverage suggestions based on declared controls
    @Default([]) List<CoverageSuggestion> coverageSuggestions,

    // Sector-specific insight
    required String sectorInsight,       // e.g. 'Healthcare orgs saw 45% more ransomware in 2024'
    @Default([]) List<String> commonThreatActors, // e.g. ['Scattered Spider', 'LockBit']

    required DateTime generatedAt,
  }) = _ThreatProfile;

  factory ThreatProfile.fromJson(Map<String, dynamic> json) =>
      _$ThreatProfileFromJson(json);
}
